server:
  port: 3000

spring:
  datasource:
    username: ${custom.mysql.username}
    password: ${custom.mysql.password}
    url: jdbc:mysql://${custom.mysql.host}:${custom.mysql.port}/${custom.mysql.table}?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useLegacyDatetimeCode=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss


# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.example.backend.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# 输出sql语句
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
